<?php
/** @var Widget $block */

use Aplazame\Payment\Block\Product\View\Widget;
use Aplazame\Serializer\Decimal;

if (!$block->isAplazameActive()) {
    return '';
}
?>
<div
    <?php if ($block->getWidgetVersion() == 'v3') : ?>
        data-aplazame-widget-instalments=""
        data-view="product"
    <?php elseif ($block->getWidgetVersion() == 'v4') : ?>
        data-aplazame-widget-instalments="v4"
        data-type="product"
        data-option-border-product="<?= /* @noEscape */ $block->getShowBorder(); ?>"
        data-option-max-amount-desired="<?= /* @noEscape */ $block->getShowMaxDesired(); ?>"
        data-option-primary-color="<?= /* @noEscape */ $block->getPrimaryColor(); ?>"
        data-option-layout="<?= /* @noEscape */ $block->getWidgetLayout(); ?>"
        data-option-align="<?= /* @noEscape */ $block->getWidgetAlign(); ?>"
    <?php else : ?>
        data-aplazame-widget-instalments="v5"
        data-type="product"
        data-option-slider="<?= /* @noEscape */ $block->getShowSlider(); ?>"
        data-option-align="<?= /* @noEscape */ $block->getWidgetAlign(); ?>"
    <?php endif; ?>
    data-amount="<?= /* @noEscape */ Decimal::fromFloat($block->getFinalPrice())->jsonSerialize(); ?>"
    data-price="<?= /* @noEscape */ $block->getPriceSelector(); ?>"
    data-country="<?= /* @noEscape */ $block->getCountryCode(); ?>"
    data-currency="<?= /* @noEscape */ $block->getCurrencyCode(); ?>"
    data-article-id="<?= /* @noEscape */ $block->getProduct()->getId(); ?>"
    data-option-legal-advice="<?= /* @noEscape */ $block->getShowLegalAdvice(); ?>"
    data-option-downpayment-info="<?= /* @noEscape */ $block->getShowDownpaymentInfo(); ?>"
    data-option-show-open-fee="<?= /* @noEscape */ $block->getShowOpenFee(); ?>"
    data-option-out-of-limits="<?= /* @noEscape */ $block->getOptionOutOfLimits(); ?>"
    <?php if ($block->getShowPayIn4()) : ?>
        data-pay-in-4=""
    <?php endif; ?>
    <?php if ( ! empty( $block->getDefaultInstalments() ) ) : ?>
		data-option-default-instalments="<?= /* @noEscape */ $block->getDefaultInstalments(); ?>"
	<?php endif; ?>
>
    <div data-aplazame-loading></div>
</div>
