<?php
/** @var Widget $block */

use Aplazame\Payment\Block\Product\View\Widget;
use Aplazame\Serializer\Decimal;

if (!$block->isAplazameActive()) {
    return '';
}
?>
<div
    data-aplazame-widget-instalments=""
    data-view="product"
    data-amount="<?php echo Decimal::fromFloat($block->getFinalPrice())->jsonSerialize(); ?>"
    data-currency="<?php echo $block->getCurrencyCode(); ?>"
    data-article-id="<?php echo $block->getProduct()->getId(); ?>"
    data-option-legal-advice="<?php echo $block->getShowLegalAdvice(); ?>"
    <?php if ( ! empty( $block->getDefaultInstalments() ) ) : ?>
		data-option-default-instalments="<?php echo $block->getDefaultInstalments(); ?>"
	<?php endif; ?>
></div>
