<?php
/** @var $block \Aplazame\Payment\Block\Js */
$config = $block->getConfig();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Aplazame_Payment/js/aplazame-init": {
                "host":"<?php echo $config->getApiBaseUri(); ?>",
                "public_key":"<?php echo $config->getPublicApiKey() ?>",
                "sandbox":<?php echo $config->isSandbox() ? 'true' : 'false' ?>
            }
        }
    }
</script>
