<?php
/** @var $block \Aplazame\Payment\Block\Js */
$config = $block->getConfig();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Aplazame_Payment/js/aplazame-init": {
                "public_key":"<?= /* @noEscape */ $config->getPublicApiKey() ?>",
                "sandbox":<?= /* @noEscape */ $config->isSandbox() ? 'true' : 'false' ?>
            }
        }
    }
</script>
