<?php

/** @var Aplazame $block */

use Aplazame\Payment\Block\Adminhtml\Product\Edit\Aplazame;

?>

<div class="entry-edit">
    <fieldset class="admin__fieldset" id="aplazame_campaigns_container">
        <legend>
            <?php echo __('Campaigns'); ?>
        </legend>
    </fieldset>
</div>

<script>
    var apiProxyEndpoint = "<?php echo $block->getUrl('aplazame/proxy/index') ?>";
    var campaignsContainer = document.getElementById("aplazame_campaigns_container");

    var articles = <?php echo json_encode($block->getArticles()) ?>;

    var dateObj = new Date();
    var currentDate = dateObj.toISOString();
    var byEndDate = function (campaign) {
        return (campaign.end_date > currentDate);
    };

    function associateArticlesToCampaign(articles, campaignId) {
        apiRequest("POST", "/me/campaigns/" + campaignId + "/articles", articles, function() {});
    }

    function removeArticlesFromCampaign(articles, campaignId) {
        var articleIds = articles.map(function (article) {
            return article.id;
        });

        apiRequest("DELETE", "/me/campaigns/" + campaignId + "/articles?article-mid=" + articleIds.join(","), null, function() {});
    }

    /**
     * @param {MouseEvent} event
     */
    function campaignToggle(event)
    {
        /**
         * @type {HTMLInputElement|EventTarget}
         */
        var checkbox = event.target;

        var campaignId = checkbox["data-campaignId"];
        if (checkbox.checked) {
            associateArticlesToCampaign(articles, campaignId);
        } else {
            removeArticlesFromCampaign(articles, campaignId);
        }
    }

    function insertCampaign(campaign) {

        var inputId = "campaign_" + campaign.id;
        /**
         * @type {HTMLInputElement|Element}
         */
        var checkbox = document.createElement("input");
        checkbox.type = "checkbox";
        checkbox.name = "campaigns[]";
        checkbox.value = campaign.id;
        checkbox.id = inputId;
        checkbox["data-campaignId"] = campaign.id;
        checkbox.addEventListener("click", campaignToggle, false);

        if (!campaign.partial) {
            checkbox.checked = true;
            checkbox.disabled = true;
            checkbox.title = "<?php echo __('The campaign applies to all products from your catalogue'); ?>";
        }

        /**
         * @type {HTMLLabelElement|Element}
         */
        var label = document.createElement("label");
        label.htmlFor = inputId;

        label.appendChild(document.createTextNode(campaign.name));

        var row = document.createElement("div");

        var control = document.createElement("div");
        control.appendChild(checkbox);
        control.appendChild(label);

        row.appendChild(control);

        row.className = "admin__field";
        label.className = "admin__field-label";
        control.className = "admin__field-control";
        checkbox.className = "admin__control-checkbox";

        campaignsContainer.appendChild(row);
    }

    function displayCampaigns(campaigns) {
        campaigns.forEach(insertCampaign);
    }

    function selectCampaigns(campaigns) {
        campaigns.forEach(function (campaign) {
            var inputId = "campaign_" + campaign.id;
            document.getElementById(inputId).checked = true;
        });

    }

    function apiRequest(method, path, data, callback) {
        new Ajax.Request(apiProxyEndpoint, {
            method: "POST",
            asynchronous: false,
            parameters: {
                method: method,
                path: path,
                data: JSON.stringify(data)
            },
            onComplete: function (transport) {
                var payload = JSON.parse(transport.responseText);

                callback(payload);
            }
        });
    }

    function getCampaigns(page = 1) {
        apiRequest("GET", "/me/campaigns?page=" + page, null, function(payload) {
            var campaigns = payload.results;

            displayCampaigns(campaigns.filter(byEndDate));

            if (payload.cursor.after != null) {
                getCampaigns(payload.cursor.after);
            }
        });
    }

    function getCampaignsFromArticle(page = 1) {
        apiRequest("GET", "/me/campaigns?articles-mid=" + articles[0].id + "&page=" + page, null, function(payload) {
            var selectedCampaigns = payload.results;

            selectCampaigns(selectedCampaigns.filter(byEndDate));

            if (payload.cursor.after != null) {
                getCampaignsFromArticle(payload.cursor.after);
            }
        });
    }

    getCampaigns();
    getCampaignsFromArticle();
</script>
